name: wear_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wear: ^1.1.0
  simple_circular_progress_bar: ^1.0.2
  intl:
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/images/

  fonts:
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
  uses-material-design: true